version: '3.8'
services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - npm_config_registry=https://registry.npmmirror.com/
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: npm run dev -- --host

volumes:
  node_modules:
